# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.16
    working_directory: ~/repo/src/github.com/LIVEauctioneers/rabbit-amazon-forwarder
    steps:
      - checkout
      - run:
          name: Go Get and Go Test ./...
          command: |
            export GOPATH=~/repo/
            git config --global url."https://$GITHUB_PRIVATE_REPOSITORY_KEY:x-oauth-basic@github.com/".insteadOf "https://github.com/"
            go get -v

            export GOBIN=${GOPATH}/bin

            go test ./... -v

  lint:
    docker:
      - image: circleci/golang:1.16
    working_directory: ~/repo/src/github.com/LIVEauctioneers/rabbit-amazon-forwarder
    steps:
      - checkout
      - run:
          name: Go linting
          command: |
            curl -s https://la-static.s3.amazonaws.com/.golangci.yml > .golangci.yml
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
            golangci-lint run

  build:
    docker:
      - image: circleci/golang:1.16
    working_directory: ~/repo/src/github.com/LIVEauctioneers/rabbit-amazon-forwarder
    steps:
      - checkout
      - run:
          name: Go Get and Go Build
          command: |
            export GOPATH=~/repo/
            git config --global url."https://$GITHUB_PRIVATE_REPOSITORY_KEY:x-oauth-basic@github.com/".insteadOf "https://github.com/"
            go get -v

            mkdir -p .bin
            CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o .bin/rabbit-amazon-forwarder .
      - persist_to_workspace:
          root: ~/repo/src/github.com/LIVEauctioneers/rabbit-amazon-forwarder/
          paths:
            - .bin
      - store_artifacts:
          path: ~/repo/src/github.com/LIVEauctioneers/rabbit-amazon-forwarder/.bin
          destination: .bin

  publish:
    docker:
      - image: circleci/golang:1.16
    working_directory: ~/repo/src/github.com/LIVEauctioneers/rabbit-amazon-forwarder
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/repo/src/github.com/LIVEauctioneers/rabbit-amazon-forwarder/
      - run:
          name: Push Docker Build
          command: |
            export GOPATH=~/repo/
            mv ~/repo/src/github.com/LIVEauctioneers/rabbit-amazon-forwarder/.bin/rabbit-amazon-forwarder ./rabbit-amazon-forwarder
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

            export VERSION=v${CIRCLE_BUILD_NUM}

            docker build -t liveauctioneers/rabbit-amazon-forwarder:${VERSION} .
            docker push liveauctioneers/rabbit-amazon-forwarder:${VERSION}

workflows:
  version: 2
  build_and_publish:
    jobs:
      - test:
          context: la_build_vars
      - build:
          context: la_build_vars
      - publish:
          context: la_build_vars
          requires:
            - build
